### PR TITLE
v0.38.12

### PR DESCRIPTION
**Pull request by jandrew**
+ Make the decimal vs scientific choice for hidden formatting more robust( issue 65 on github )
	+ Adding tests for hidden tabs rows columns and cells in the worksheet and cell
	+ Adding the method 'get_merged_areas' to match ~::ParseExcel
	+ For compatability purposes this package will now test (during import) to see if it's being
		used in Spreadsheet::Read (potential future) and automatically push the :like_ParseExcel
		tag on the end of the tag list so that it will behave consistently to ParseExcel for a common
		reader. (This is a beta feature and not guaranteed to remain)
	+ This package now supports stacked flags (not that there exists so many already)
		The purpose of this is as I run into additional use cases the intersection of
		the flags I support and the flags that are desired by the user may require some juggling.
		Where flags disagree in their defaults the last flag passed will be used.  This should allow
		for the proliferation of flags for specialty cases without having to explicitly build one
		for each use case. (At some point though you may just want to use the attributes).
		The test for this is t/Spreadsheet/XLSX/Reader/06-stacked_flags.t

### CODE REVIEW

**Comment by Tux** [comment]
This still PASS's Spreadsheet::Read (as available on git by the time of writing)

**Comment by jandrew** [comment]
Tux,  Thanks for the update its good to know your system passes even though TravisCI fails.  It means that I correctly identified the area of code that needs focus.   I think that the system different fails are occurring in the precision differences of systems between the 16th and the 29th digit and I need to find an alternate way to get a consistent result.  (Still searching)

**Comment by Tux** [comment]
Note that the test error is still there
```
not ok 103 - And check the returned value: 0.005

#   Failed test 'And check the returned value: 0.005'
#   at t/Spreadsheet/XLSX/Reader/51-percent_file_bug.t line 170.
#          got: '5E-03'
#     expected: '0.005'
```
I just tested Spreadsheet::Read against uninstalled build on git checkout using $PERL5LIB

**Comment by jandrew** [comment]
OK, Thanks

**Pull request merged**
